### ISSUE TITLE
Cfg order

### ISSUE THREAD

**Issue by dtolnay** [TedDriggs/syn-select#3]
Consider this input and the query `"m::S"`:

```rust
#[cfg(outer)]
mod m {
    /// doc
    #[cfg(inner)]
    struct S;
}
```

The current result is:

```rust
/// doc
#[cfg(inner)]
#[cfg(outer)]
struct S;
```

I would like to suggest that it should be:

```rust
/// doc
#[cfg(outer)]
#[cfg(inner)]
struct S;
```

in which the attributes closest to the final item in the original code continue to be closest to the final item in the selection result, with the exception that doc comments on the inner item may come before cfgs on the outer item. The exception is because the rustfmt style guide recommends that ["Doc comments should come before attributes"](https://github.com/rust-dev-tools/fmt-rfcs/blob/d3c475f28fe9da426bf40abbf0887462a52b6e07/guide/guide.md#doc-comments).

**Comment by TedDriggs** [comment]
Putting outer elements at the front is easy enough, but what should I do if the input code doesn't adhere to the rustfmt guide? Additional reordering input attributes seems like a bad idea.

**Comment by dtolnay** [comment]
I would insert outer attributes immediately after any leading doc attributes.

```diff
  /// doc
  /// doc
+ #[cfg(outer)]
  #[cfg(inner)]
  /// doc
  #[cfg(inner2)]
```
