### ISSUE TITLE
Current Debug impl for Selector should be the Display impl; Debug impl should be derived

### ISSUE THREAD

**Issue by dtolnay** [TedDriggs/syn-select#5]

**Comment by TedDriggs** [comment]
Fixed by #6

**Comment by dtolnay** [comment]
Please reopen -- #6 does not affect the Debug / Display impls of Selector.

**Comment by TedDriggs** [comment]
@dtolnay my thinking on this one was that I didn't want to leak internals of the `Selector` impl. Is there a reason the two shouldn't both be the same?

**Comment by dtolnay** [comment]
The Debug impl is supposed to leak internals so that the person debugging can understand the behavior of their program. See for example `println!("{:?}", core::any::TypeId::of::<()>())`.

The Display impl and Debug impl for Selector should not be the same because the Display impl is not maximally helpful in revealing how the program works.
